language:
  # PLUGIN THINGS
  prefix: "&6[&9SimpleTools&6]"
  configReloaded: "&aSe ha recargado la configuración!"
  # ERRORS
  onlyPlayerCommand: "&cEste comando sólo lo puede ejecutar un jugador"
  noPermission: "&cNo tienes permisos para eso!"
  tooManyArguments: "&cDemasiados argumentos!"
  playerRequired: "&cDebes especificar un jugador!"
  invalidArgument: "&cArgumento no válido!"
  # GLOBAL CHEST COMMAND
  globalChestTitle: "&8Cofre global"
  # SPAWN COMMAND
  spawnSelf: "&7Has sido teletransportado al spawn"
  spawnYouOthers: "&7Has teletransportado a &a%victim% &7al spawn"
  spawnOthersYou: "&7Has sido teletransportado al spawn por &a%sender%"
  # DISCORD COMMAND
  discordMsg: "&7Aquí tienes nuestro discord, &a%sender% &7:\n&9&nhttps://discord.gg/HHtQ8wU2TK"
  # FREE FALL COMMAND
  freefallMsg: "&d&lHas sido teletransportado aquí arriba por nuv" 
version: 1.3.1