language:
  #prefix
  prefix: "§6[§9SimpleTools§6]"
  #Errors
  onlyPlayerCommand: "§cEste comando sólo lo puede ejecutar un jugador"
  noPermission: "§cNo tienes permisos para esto, put!"
  tooManyArguments: "§cDemasiados argumentos!"
  playerRequired: "§cDebes especificar un jugador!"
  # Spawn Command
  spawnSelf: "§7Has sido teletransportado al spawn"
  spawnYouOthers: "§7Has teletransportado a §a%victim% §7al spawn"
  spawnOthersYou: "§7Has sido teletransportado al spawn por §a%sender%"
  # Discord Command
  discordMsg: "§7Aquí tienes nuestro discord, §a%sender% §7:\n§9§nhttps://discord.gg/HHtQ8wU2TK"
  # Free Fall Command
  freefallMsg: "§d§lHas sido teletransportado aquí arriba por nuv" 
